name: Release Drafter

on:
  workflow_run:
    workflows: 
      - Build
    types:
      - completed
    branches:
      - 'master'

permissions:
  contents: read

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: send telegram message on fail build
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} conclusion: ${{ github.event.workflow_run.conclusion }}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
      contents: write
      pull-requests: write
    steps:      
      - name: 🚀 Create Pre-Release version
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🍏 ${{ github.actor }}
            Commit message: ${{ github.event.commits[0].message }}
            Repository: https://github.com/${{ github.repository }}
            Commit: https://github.com/${{ github.repository }}/commit/${{github.sha}}
