name: Lighthouse CI

on:
  workflow_run:
    workflows: 
      - 'Release Pages'
    types:
      - completed
    branches:
      - 'master'
# on:
#   push:
    # branches:
    #   - master

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        env:
          URL_DOMAIN: 'jekyll.bulch.ru'
        with:
          urls: |
            https://$URL_DOMAIN/
            https://$URL_DOMAIN/works
            https://$URL_DOMAIN/works/web/bulch.ru
          budgetPath: .github/lighthouse/budget.json
          configPath: .github/lighthouse/lighthouserc-assertions.json
          uploadArtifacts: true
          temporaryPublicStorage: true
