name: Release
on:
  workflow_run:
    workflows: 
      - Release Drafter
    types:
      - completed
    branches:
      - 'master'

env:
  HUSKY: '0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: release-drafter/release-drafter@master
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
