name: Release
on:
  workflow_dispatch:

env:
  HUSKY: '0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Create Release version
        uses: release-drafter/release-drafter@master
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
