name: Release

on:
  workflow_run:
    workflows: 
      - Build
    types:
      - completed
    branches:
      - 'master'

permissions:
  contents: read

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
      - name: Send Telegram Message
        uses: cbrgm/telegram-github-action@v1 
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: "FAIL! Conclusion: ${{ github.event.workflow_run.conclusion }}"

  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Semver
        id: semver-tag
        uses: gandarez/semver-action@master
        with:
          branching_model: "git-flow"
          prefix: "v"
          prerelease_id: "alpha"
          main_branch_name: "master"
          develop_branch_name: "develop"
          patch_regex: "^fix/.+"
          minor_regex: "^feat/.+"
          major_regex: "^major/.+"
          build_regex: "^build/.+"
          hotfix_regex: "^hotfix/.+"
          exclude_regex: "^ignore/.+"

      - name: "Created tag"
        run: echo "tag ${{ steps.semver-tag.outputs.semver_tag }}"
      
      - name: 🚀 Create Release version
        uses: release-drafter/release-drafter@v5
        with:
          version: ${{ steps.semver-tag.outputs.semver_tag }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Send Telegram Message
        uses: cbrgm/telegram-github-action@v1 
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: "New vertsion ${{ steps.semver-tag.outputs.semver_tag }}"
