name: Release

on:
  workflow_run:
    workflows: 
      - Build
    types:
      - completed
    branches:
      - 'master'

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'

  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - id: semver-tag
        uses: gandarez/semver-action@master
        with:
          branching_model: "git-flow"
          prefix: "v"
          prerelease_id: "alpha"
          main_branch_name: "master"
          develop_branch_name: "develop"
          patch_regex: "^fix/.+"
          minor_regex: "^feat/.+"
          major_regex: "^major/.+"
          build_regex: "^build/.+"
          hotfix_regex: "^hotfix/.+"
          exclude_regex: "^ignore/.+"

      - name: "Created tag"
        run: echo "tag ${{ steps.semver-tag.outputs.semver_tag }}"
      
      - name: 🚀 force update major tag
        run: |
          git tag v${{ steps.semver-tag.outputs.semver_tag }} -f
          git push origin refs/tags/v${{ steps.semver-tag.outputs.semver_tag }} -f
      
      - name: 🚀 Release version
        uses: release-drafter/release-drafter@master
        with:
          version: ${{ steps.semver-tag.outputs.semver_tag }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Send Telegram Message
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: "New vertsion v${{ steps.semver-tag.outputs.semver_tag }}"
