name: Validator

on:
  workflow_run:
    workflows: 
      - 'Build'
    types:
      - completed

jobs:
  validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: jekyll_site
          path: _site

      - name: HTML5Validator
        uses: Cyb3r-Jak3/html5validator-action
        with:
          root: _site

      - uses: actions/upload-artifact@v3
        with:
          name: log
          path: log.log
